-- Add new Asset Classes
ALTER TYPE "AssetClass" ADD VALUE 'DEBT';
ALTER TYPE "AssetClass" ADD VALUE 'PRECIOUS_METALS';

-- Add new Asset Sub-Classes
ALTER TYPE "AssetSubClass" ADD VALUE 'COMMODITY';
ALTER TYPE "AssetSubClass" ADD VALUE 'DEBT_FUND';
ALTER TYPE "AssetSubClass" ADD VALUE 'FIXED_DEPOSIT';
ALTER TYPE "AssetSubClass" ADD VALUE 'GOLD_22K';
ALTER TYPE "AssetSubClass" ADD VALUE 'GOLD_24K';
ALTER TYPE "AssetSubClass" ADD VALUE 'GOLD_ETF';
ALTER TYPE "AssetSubClass" ADD VALUE 'HOUSE';
ALTER TYPE "AssetSubClass" ADD VALUE 'PLOT';
ALTER TYPE "AssetSubClass" ADD VALUE 'SILVER_BAR';

